modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "allthetrims"
version = "${version}"
displayName = "AllTheTrims"
authors = "Bawnorton"
description = '''
A mod that allows any item to be a trim material and makes all armour trimmable.
'''
#logoFile = ""

[[mixins]]
config = "allthetrims.mixins.json"

[[mixins]]
config = "allthetrims-common.mixins.json"

[[dependencies.allthetrims]]
modId = "minecraft"
required = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.allthetrims]]
modId = "architectury"
required = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"